server:
  port: 8085

spring:
  application:
    name: ms2-redis
  
  json:
    use:
      type:
        headers: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    function:
      
      definition: stockRequested;processBatch

    stream:
      #default-binder: rabbit
      default-binder: kafka
      bindings:
        stockRequested-in-0:
          destination: stock.requested
          group: redis-consumer
          content-type: application/json
        
        processBatch-in-0:
          destination: batch.process.requested
          group: redis-consumer
          content-type: application/json
        
        batchCompleted-out-0:
          destination: batch.completed
          content-type: application/json
      
      rabbit:
        binder:
          header-mode: headers