spring:
  cloud:
    stream:
      default-binder: kafka
      #default-binder: rabbit
      
      bindings:
        stockRequested-out-0:
          destination: stock.requested
          content-type: application/json
        
        processBatch-out-0:
          destination: batch.process.requested
          content-type: application/json
        
        getStockNews-out-0:
          destination: analysis.requested
          content-type: application/json

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest