spring:
  application:
    name: ms2-postgres
  
  json:
    use:
      type:
        headers: false

  cloud:
    stream:
      function:
        definition: processStockData
      
      kafka:
        binder:
          configuration:
            spring.json.trusted.packages: "*"

      #default-binder: rabbit
      default-binder: kafka      
      bindings:

        processStockData-in-0:
          destination: analysis.requested
          group: postgres-consumer
          content-type: application/json

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest